import { linguaCorrente, type Lingua } from '@/i18n/lingua';
import { traduci, type Chiave, type Parametri } from '@/i18n/t';
export type Parole = Dizionario;

// I testi stanno nel catalogo (i18n/it|en/marketsPage.ts): qui solo la forma che le viste usano.
function costruisci(l: Lingua) {
  const tr = (k: Chiave, p?: Record<string, string | number | null | undefined>) => traduci(l, k, p as Parametri | undefined);
  return {
    title: tr('marketsPage.title'),
    searchLabel: tr('marketsPage.searchLabel'),
    searchHint: tr('marketsPage.searchHint'),
    searchOther: tr('marketsPage.searchOther'),
    searchRecent: tr('marketsPage.searchRecent'),
    searchResults: (q: string) => tr('marketsPage.searchResults', { q }),
    searchNone: tr('marketsPage.searchNone'),
    searchFailed: (e: string) => tr('marketsPage.searchFailed', { e }),
    updatedAt: (h: string) => tr('marketsPage.updatedAt', { h }),
    notUpdated: tr('marketsPage.notUpdated'),
    auto: tr('marketsPage.auto'),
    autoHint: tr('marketsPage.autoHint'),
    refresh: tr('marketsPage.refresh'),
    refreshing: tr('marketsPage.refreshing'),
    overviewError: (e: string) => tr('marketsPage.overviewError', { e }),
    retry: tr('marketsPage.retry'),
    emptyLoading: tr('marketsPage.emptyLoading'),
    emptyError: tr('marketsPage.emptyError'),
    empty: tr('marketsPage.empty'),
    favorites: tr('marketsPage.favorites'),
    favoritesManage: tr('marketsPage.favoritesManage'),
    favoritesSuggested: tr('marketsPage.favoritesSuggested'),
    favoritesError: (e: string) => tr('marketsPage.favoritesError', { e }),
    indices: tr('marketsPage.indices'),
    regions: tr('marketsPage.regions'),
    regionNames: { am: tr('marketsPage.regionNames_am'), eu: tr('marketsPage.regionNames_eu'), as: tr('marketsPage.regionNames_as') } as Record<string, string>,
    commodityGroups: { met: tr('marketsPage.commodityGroups_met'), ene: tr('marketsPage.commodityGroups_ene'), agr: tr('marketsPage.commodityGroups_agr') } as Record<string, string>,
    equities: tr('marketsPage.equities'),
    equitiesByCountry: tr('marketsPage.equitiesByCountry'),
    countryNames: { US: tr('marketsPage.countryNames_US'), IT: tr('marketsPage.countryNames_IT'), DE: tr('marketsPage.countryNames_DE'), FR: tr('marketsPage.countryNames_FR'), UK: tr('marketsPage.countryNames_UK'), JP: tr('marketsPage.countryNames_JP'), CN: tr('marketsPage.countryNames_CN'), IN: tr('marketsPage.countryNames_IN'), BR: tr('marketsPage.countryNames_BR') } as Record<string, string>,
    movers: tr('marketsPage.movers'),
    moversScope: tr('marketsPage.moversScope'),
    moversStocks: tr('marketsPage.moversStocks'),
    moversAll: tr('marketsPage.moversAll'),
    moversStocksHint: tr('marketsPage.moversStocksHint'),
    moversAllHint: tr('marketsPage.moversAllHint'),
    gainers: tr('marketsPage.gainers'),
    losers: tr('marketsPage.losers'),
    moversEmpty: tr('marketsPage.moversEmpty'),
    moversError: (e: string) => tr('marketsPage.moversError', { e }),
    kindIndex: tr('marketsPage.kindIndex'),
    kindCommodity: tr('marketsPage.kindCommodity'),
    kindFx: tr('marketsPage.kindFx'),
    kindFuture: tr('marketsPage.kindFuture'),
    commodities: tr('marketsPage.commodities'),
    currencies: tr('marketsPage.currencies'),
    ratesFutures: tr('marketsPage.ratesFutures'),
    rates: tr('marketsPage.rates'),
    futures: tr('marketsPage.futures'),
    yieldNote: tr('marketsPage.yieldNote'),
    back: tr('marketsPage.back'),
    previousClose: tr('marketsPage.previousClose'),
    consensus: (r: string) => tr('marketsPage.consensus', { r }),
    target: (v: string) => tr('marketsPage.target', { v }),
    inFavorites: tr('marketsPage.inFavorites'),
    addFavorite: tr('marketsPage.addFavorite'),
    addFavoriteTitle: tr('marketsPage.addFavoriteTitle'),
    removeFavoriteTitle: tr('marketsPage.removeFavoriteTitle'),
    favoriteReadFailed: (e: string) => tr('marketsPage.favoriteReadFailed', { e }),
    favoriteUnconfirmed: (e: string) => tr('marketsPage.favoriteUnconfirmed', { e }),
    quoteError: (e: string) => tr('marketsPage.quoteError', { e }),
    chart: tr('marketsPage.chart'),
    news: tr('marketsPage.news'),
    newsAll: tr('marketsPage.newsAll'),
    newsTabs: tr('marketsPage.newsTabs'),
    newsLoading: tr('marketsPage.newsLoading'),
    newsEmpty: tr('marketsPage.newsEmpty'),
    newsError: (e: string) => tr('marketsPage.newsError', { e }),
    newsPartial: (e: string) => tr('marketsPage.newsPartial', { e }),
    newsByName: (q: string) => tr('marketsPage.newsByName', { q }),
    newsSource: (f: string) => tr('marketsPage.newsSource', { f }),
    newsSourceTicker: tr('marketsPage.newsSourceTicker'),
    newsSourceSearch: tr('marketsPage.newsSourceSearch'),
    newsSourceUnknown: tr('marketsPage.newsSourceUnknown'),
    translate: tr('marketsPage.translate'),
    translating: tr('marketsPage.translating'),
    showOriginal: tr('marketsPage.showOriginal'),
    showTranslated: tr('marketsPage.showTranslated'),
    translateHint: tr('marketsPage.translateHint'),
    translatedNote: (costo: string | null) => costo ? tr('marketsPage.translatedNote_cost', { costo }) : tr('marketsPage.translatedNote'),
    translateFailed: (e: string) => tr('marketsPage.translateFailed', { e }),
    translatePartial: tr('marketsPage.translatePartial'),
    translateNotConfigured: (v: string) => tr('marketsPage.translateNotConfigured', { v }),
    keyData: tr('marketsPage.keyData'),
    stats: { cap: tr('marketsPage.stats_cap'), pe: tr('marketsPage.stats_pe'), fpe: tr('marketsPage.stats_fpe'), eps: tr('marketsPage.stats_eps'), beta: tr('marketsPage.stats_beta'), div: tr('marketsPage.stats_div'), vol: tr('marketsPage.stats_vol'), avgVol: tr('marketsPage.stats_avgVol'), short: tr('marketsPage.stats_short'), target: tr('marketsPage.stats_target'), ev: tr('marketsPage.stats_ev'), evEbitda: tr('marketsPage.stats_evEbitda'), evSales: tr('marketsPage.stats_evSales'), peg: tr('marketsPage.stats_peg'), pb: tr('marketsPage.stats_pb'), fcf: tr('marketsPage.stats_fcf') },
    low52: tr('marketsPage.low52'),
    high52: tr('marketsPage.high52'),
    financials: tr('marketsPage.financials'),
    financialsTabs: tr('marketsPage.financialsTabs'),
    income: tr('marketsPage.income'),
    balance: tr('marketsPage.balance'),
    cashflow: tr('marketsPage.cashflow'),
    incomeTitle: tr('marketsPage.incomeTitle'),
    balanceTitle: tr('marketsPage.balanceTitle'),
    cashflowTitle: tr('marketsPage.cashflowTitle'),
    financialsLoading: tr('marketsPage.financialsLoading'),
    financialsError: tr('marketsPage.financialsError'),
    rowLabel: tr('marketsPage.rowLabel'),
    holders: tr('marketsPage.holders'),
    holdersTabs: tr('marketsPage.holdersTabs'),
    ownership: tr('marketsPage.ownership'),
    profile: tr('marketsPage.profile'),
    companyProfile: tr('marketsPage.companyProfile'),
    holdersLoading: tr('marketsPage.holdersLoading'),
    ownershipLabels: { insidersPercentHeld: tr('marketsPage.ownershipLabels_insidersPercentHeld'), institutionsPercentHeld: tr('marketsPage.ownershipLabels_institutionsPercentHeld'), institutionsFloatPercentHeld: tr('marketsPage.ownershipLabels_institutionsFloatPercentHeld'), institutionsCount: tr('marketsPage.ownershipLabels_institutionsCount') } as Record<string, string>,
    topHolders: tr('marketsPage.topHolders'),
    profileEmpty: tr('marketsPage.profileEmpty'),
    sourceOriginal: tr('marketsPage.sourceOriginal'),
    moversCountryOff: (cc: string, motivo: string | null | undefined) => motivo ? tr('marketsPage.moversCountryOff', { cc, motivo }) : tr('marketsPage.moversCountryOffBare', { cc }),
    moversDeclared: (motivo: string) => tr('marketsPage.moversDeclared', { motivo }),
    moversSource: (fonte: string) => tr('marketsPage.moversSource', { fonte }),
    equitiesOff: (motivo: string | null | undefined) => motivo ? tr('marketsPage.equitiesOff', { motivo }) : tr('marketsPage.equitiesOffBare'),
  };
}

type Dizionario = ReturnType<typeof costruisci>;
const cache = new Map<Lingua, Dizionario>();

export function parole(): Dizionario {
  const l = linguaCorrente();
  let d = cache.get(l);
  if (!d) { d = costruisci(l); cache.set(l, d); }
  return d;
}
