"""Substantive but entirely fictional research for offline layout/protocol replay.

No claim here is a source about a real issuer. This is intentionally a distinct
analytical text for every section, not repetitions used to force a page count.
"""
from copy import deepcopy

from bellomberg.core.trade_idea_contract import validate_result

TEXT = {
"executive": ("Investment conclusion and the question that matters", """
Synthetic Components is an invented supplier used to test this research workflow. The investment question is whether qualification with industrial customers creates durable pricing power or merely makes the supplier difficult to replace until the next platform redesign. The archived synthetic evidence supports a narrower conclusion than the optimistic PM thesis. Retention is strong within installed programs, but renewal economics remain contestable. A position would therefore depend on cash returns through a replacement cycle, rather than on extrapolating the recent order recovery. This distinction governs the committee's valuation, its downside case and the conditions attached to any proposal. [src: synthetic_archive]

The positive case combines established production know-how, a diversified set of end markets and a development process that embeds the supplier in the customer's engineering schedule. These characteristics may protect existing revenue when procurement teams reduce discretionary spending. They do not remove competition at the design stage, eliminate the need for reinvestment or make backlog equivalent to cash. The committee treats the backlog as evidence of activity and tests its convertibility separately. It also separates orders linked to a customer's inventory rebuilding from orders supported by final consumption. Those two sources of demand have different persistence and implications for normalized margins. [src: synthetic_archive]

The principal counterargument concerns the quality of incremental profitability. A recovery in utilization can lift reported earnings before the business has demonstrated sustainable pricing or a better product mix. A favorable operating comparison may therefore coexist with weak free cash flow, especially if customers extend payment terms while the supplier funds new inventory. The value of the business depends on how much of its apparent improvement survives that working-capital cycle. The committee has not treated management's confidence as evidence that these frictions have disappeared. It asks which contractual provisions, customer behavior and balance-sheet movements actually support the assertion. [src: synthetic_archive]

The decision framework uses independently specified downside, central and upside cases. They are conditional descriptions of the business rather than forecasts with invented probabilities. The downside case tests renewed inventory correction and competitive pricing at platform renewals. The central case assumes an orderly conversion of the existing programs, with reinvestment remaining necessary. The upside case requires evidence that engineering content and mix improve the economics of the installed base. Any price-to-value comparison must use the same share class, currency, valuation date and assumptions as the linked workbook. A fresh market quote is not silently substituted for that dated analytical basis. [src: synthetic_archive]

The most useful next evidence would be customer-level program renewals, a reconciliation of order intake to shipments and a cash bridge that distinguishes temporary absorption from structural investment. These are more informative than another broad statement that demand is healthy. A positive committee judgment can coexist with a decision to wait if the portfolio's liquidity, exposure or risk budget does not support implementation. Conversely, a rejected investment idea may still have a complete and valid valuation model worth preserving. The workflow keeps those distinctions visible so that neither a technical delivery state nor an attractive narrative substitutes for an actionable investment decision. [src: synthetic_archive]
"""),
"pm_view": ("The PM thesis against the evidence", """
The PM's deliberately optimistic test view describes the business as protected from a downturn by customer switching costs. It is a hypothesis for investigation, not a factual input into the forecast. The committee first decomposes that view into observable claims: whether customers can qualify an alternative, how long qualification takes, whether contract terms protect volume, and whether the supplier earns an adequate return after the investment needed to remain qualified. A supplier can be operationally important without possessing the bargaining power implied by the original thesis. Preserving the PM's wording in the record helps identify exactly where the analysis agrees or disagrees. [src: synthetic_archive]

The evidence supports the claim that changing an incumbent supplier can be costly within an active product program. Customers have to repeat testing, document reliability and manage the risk of disrupting their own production. That creates a real obstacle to an abrupt switch, but it is not the same as a perpetual franchise. Procurement departments can introduce alternative suppliers for the next design, dual-source selected components or shift commercial pressure to annual price negotiations. The committee therefore accepts switching friction as an advantage with boundaries. It rejects the stronger inference that the advantage insulates every revenue stream from volume or pricing pressure. [src: synthetic_archive]

A second part of the PM view assumes that strong engineering relationships will convert into higher margins. That outcome is possible, but the relationship between design effort and value capture is not automatic. Some engineering work is paid for through product pricing; other work is effectively a condition of remaining on a customer's approved supplier list. Without a clear contract-level return bridge, increasing technical complexity might increase costs as quickly as it increases revenue. The relevant evidence is the economics of renewed programs after development spending, tooling and production ramp costs. This is why the committee requests cohort evidence rather than treating total research expenditure as proof of a moat. [src: synthetic_archive]

The variant view is consequently more conditional than the PM's starting position. The committee sees a potentially durable position in particular applications, supported by certification and process knowledge, but requires evidence that value capture persists through redesign and procurement cycles. It would change its mind favorably if customer renewals preserved contribution margins while cash conversion improved without reduced maintenance investment. It would change its mind negatively if retention depended on price concessions, extended receivables or unrecovered tooling. These conditions make disagreement useful: they turn an abstract debate over quality into a set of observations that can discriminate between competing explanations. [src: synthetic_archive]

The retained dissent concerns how quickly the evidence can become decisive. The optimistic interpretation expects a small number of favorable renewals to confirm the franchise. The more cautious interpretation notes that customers and platforms have different economics, so a selected success may not represent the portfolio of programs. The Capo does not resolve that disagreement by counting specialist votes. It weighs the relevance and completeness of the underlying evidence and keeps the unresolved issue in the monitoring conditions. No recommendation is promoted merely because it matches the PM's preference; the research response identifies both the supported portion of the thesis and the parts that remain unproved. [src: synthetic_archive]
"""),
"business": ("Business model, competitive position and comparability", """
The fictional business develops and manufactures application-specific components for industrial equipment. Its commercial model joins engineering support with serial production: design work helps win a program, and production revenue follows the customer's launch and replacement schedule. This creates different economic phases within the same reported segment. A mature platform can generate cash with limited incremental development, while a new platform consumes engineering capacity and working capital before reaching efficient utilization. An aggregate margin obscures this lifecycle. The committee therefore examines program maturity and capital requirements before drawing conclusions from the consolidated result. [src: synthetic_archive]

The relevant competitive assets are process reliability, documentation, accumulated application knowledge and the ability to support customers during qualification. None should be conflated with a legal monopoly. A competitor may possess a technically acceptable alternative and still need time to demonstrate reliable delivery. Equally, a customer may tolerate a higher component price if the operational cost of failure is much larger. The supplier's advantage is strongest where these frictions are material and weakest where specifications are standardized. The research separates those applications instead of applying a single quality premium to every product in the business. [src: synthetic_archive]

Peer comparison must reflect those differences. A standard-parts distributor, a proprietary systems vendor and a contract manufacturer can all serve similar customers while having very different gross margins, capital intensity and exposure to inventory. Comparing their headline valuation multiples would not isolate mispricing. The committee would reconcile accounting policies, ownership of tooling, outsourced production, acquisition history and geographic mix before using peers as a cross-check. It also distinguishes economic comparability from ticker convenience. An accessible domestic quote is not an acceptable substitute for the selected share class or for a peer whose business model has actually been verified. [src: synthetic_archive]

Customer concentration is another source of ambiguity. A long relationship with a large customer can be evidence of trust, but it can also transfer negotiating power to that customer. The committee tests whether the supplier owns intellectual property that can be sold across programs, whether development expenditure is reimbursed, and whether cancelled programs leave stranded assets. It also examines the direction of dependence: losing a small but technologically important program might damage future opportunities more than its current revenue suggests. Those effects require contract and product evidence; they cannot be inferred from a customer logo displayed in a presentation. [src: synthetic_archive]

The business-quality conclusion is therefore application-specific. The synthetic record suggests attractive retention within established programs but does not demonstrate uniformly high returns on new wins. The monitoring plan focuses on renewal cohorts, development recoverability and the reuse of engineering knowledge across customers. Evidence of improving reuse would strengthen the thesis by reducing the investment required for each incremental program. Evidence that every win requires bespoke spending would weaken the argument for operating leverage. This framework leaves room for a high-quality business while refusing to capitalize a broad moat claim before its unit economics have been demonstrated. [src: synthetic_archive]
"""),
"financial_quality": ("Earnings quality and the balance-sheet bridge", """
The accounting analysis begins with the distinction between reported operating improvement and cash that can ultimately be distributed to shareholders. The fictional company's income statement benefits when production volumes absorb fixed manufacturing costs, but that improvement may arrive before cash is collected from customers. Inventory built for anticipated launches and receivables extended during a recovery can consume liquidity even when earnings look stronger. The committee therefore follows the path from sales to operating profit, operating cash flow and investment, asking where timing differences arise and whether they are likely to reverse. [src: synthetic_archive]

Revenue recognition requires particular attention around customer acceptance and shipment cutoffs. A shipment that has left the factory may not represent an unconditional right to payment if qualification, inspection or installation obligations remain. The synthetic archive is treated as a controlled example of the questions to ask, not as a certification of a real accounting policy. The analytical approach would reconcile reported revenue with receivables, contract balances, credit notes and subsequent collections. A divergence does not establish misconduct by itself, but it prevents the committee from treating reported growth as fully converted demand until the underlying contractual explanation is clear. [src: synthetic_archive]

Working capital is reviewed by economic function rather than by a convenient net total. Trade receivables, ordinary inventory and operating payables belong to the production cycle; financing balances, lease liabilities and obligations to purchase equipment require separate treatment. Mixed balance-sheet captions need supporting notes before their contents can be assigned. The committee does not create a residual operating asset simply to make the bridge add up. Reconciliation is necessary but not sufficient: a mathematically balanced cash-flow model can still be economically wrong if the classifications are wrong. The model remains incomplete wherever the necessary classification evidence is unavailable. [src: synthetic_archive]

Reinvestment is equally important to the quality of earnings. Maintenance expenditure preserves existing capacity and reliability, while growth expenditure supports additional programs; the distinction can be uncertain when equipment serves both purposes. Capitalized development requires a consistent treatment across operating profit, amortization and invested capital. The committee would not add back development amortization while ignoring the cash needed to replenish the asset. It also tests whether unusually low investment temporarily flatters free cash flow. A sustainable cash return must fund the capabilities that support the franchise, including quality systems and production resilience, rather than assuming that historical expenditure was discretionary. [src: synthetic_archive]

The balance-sheet conclusion links solvency, operating flexibility and shareholder value without collapsing them into one leverage statistic. Liquidity can be constrained by debt maturities, covenant definitions or cash held outside the relevant parent perimeter. A consolidated cash balance is not automatically distributable cash. The valuation bridge must identify financial debt, leases, minority claims and non-operating assets consistently with the chosen cash-flow method. The committee records missing reconciliation evidence as a specific research gap and explains which conclusion it prevents. It does not substitute a familiar industry ratio for the unavailable information or describe a partial accounting bridge as a complete model. [src: synthetic_archive]
"""),
"valuation": ("Valuation method and the path from evidence to value", """
An operating cash-flow method is appropriate for the fictional manufacturing case only because the business perimeter and the relationship between operations and reinvestment can be represented coherently. This choice would be unsuitable for a bank whose debt is integral to production, or for an investment vehicle better described through its assets and claims. Method selection precedes the calculation. The committee starts with verified identity, reporting currency, share class and financial perimeter, then checks whether the available evidence supports the required driver definitions. The presence of a sector label alone does not authorize a discounted cash-flow model. [src: synthetic_archive]

The linked common workbook is the calculation source for value. The PDF describes the assumptions and their economic meaning; it does not maintain an alternative spreadsheet inside the narrative. Revenue should be built from defensible volume, price and mix relationships where the evidence allows, with margins reflecting the costs and capacity needed to deliver that revenue. Reinvestment follows the operational scenario, including working capital and development requirements. The terminal state is checked for consistency with replacement investment, sustainable profitability and the capital required to support growth. A smooth forecast curve is not itself evidence that the business can reach that state. [src: synthetic_archive]

Discounting requires matching the cash flow, currency and risk framework. Nominal cash flows cannot be combined casually with real discount rates, and a market reference from another currency cannot be transplanted without explanation. The committee distinguishes observable inputs from analyst judgments, records their dates and keeps the sources alongside the model. A discount rate is not adjusted merely to produce a desired target price. If the economic basis of a component cannot be established, the uncertainty is stated and its consequence for usability remains visible. Sensitivity analysis can show the importance of an assumption, but it cannot repair an unsupported assumption. [src: synthetic_archive]

The bridge from enterprise value to the selected equity claim receives the same attention as the operating forecast. Cash and debt must share a coherent perimeter and date; lease treatment must match the operating cash flow; minority interests and other claims must not be counted twice or omitted. Dilution and share-class economics affect what an investor actually owns. A correct business value with an incorrect claim bridge can yield a misleading per-share conclusion. The common engine's arithmetic controls are therefore complemented by an explicit explanation of the perimeter, the classification decisions and any items that remain unresolved. [src: synthetic_archive]

Investment attractiveness is evaluated after model usability, not folded into it. A complete model can support a rejection when the market price offers inadequate compensation for the risks. An attractive qualitative thesis can remain non-actionable when the model lacks an essential input. The research preserves a valid workbook in both positive and negative cases, with the exact snapshot and generation identifiers that bind it to the report. Where no workbook passes the controls, the delivery names the missing inputs or authorization. It does not fabricate an attachment, relabel a diagnostic file as complete or borrow a nearby workbook from another issuer. [src: synthetic_archive]
"""),
"scenarios": ("Scenarios, sensitivities and market expectations", """
The scenario framework is designed to distinguish competing business mechanisms. In the downside case, the customer restocking cycle fades before new platforms reach efficient production, leaving the supplier with inventory and development commitments that were undertaken during the recovery. In the central case, existing programs convert to shipments without exceptional pricing gains, and reinvestment remains sufficient to maintain reliability. In the upside case, engineering content and reuse improve the economics of new programs while established products continue to generate cash. These descriptions are internally linked operating states, not independent favorable adjustments chosen line by line. [src: synthetic_archive]

The downside analysis asks how the business responds when volume weakens. Variable costs may fall quickly, but staffing, certification work and customer support cannot necessarily be reduced at the same pace. Inventory may become less liquid exactly when cash collection slows. The committee examines the sequence of those effects rather than applying a uniform haircut to revenue and assuming unchanged margins. It also asks which investments can be deferred without damaging the long-term franchise. Cutting expenditure can preserve cash temporarily while increasing future reliability or product-development risk, so the apparent benefit must be judged over the relevant operating cycle. [src: synthetic_archive]

The central case is a reference path, not a prediction that the most convenient outcome will occur. It should explain what happens if the existing evidence is broadly representative and no new competitive advantage emerges. Its purpose is to make the committee's assumptions observable and revisable. When new evidence arrives, the researcher can identify whether volume conversion, pricing, cost absorption or capital efficiency changed. This is more informative than treating every difference from the forecast as a generic surprise. A scenario is useful when it clarifies the source of disagreement and supports a disciplined update of the investment thesis. [src: synthetic_archive]

The upside case has to earn its assumptions through a plausible operating mechanism. Higher engineering content may support pricing, but only if customers value it and competitors cannot offer equivalent performance cheaply. Better utilization can improve margins, but capacity constraints or additional tooling may offset some of the benefit. A stronger competitive position can extend the duration of returns, but it does not remove the need to reinvest. The committee explicitly identifies the observations that would support these improvements and avoids assigning numerical probabilities where the evidence does not support calibrated estimates. Potential outcomes and estimated likelihoods are separate claims. [src: synthetic_archive]

Sensitivity analysis complements the scenarios by showing which individual assumptions most affect the result. It is especially useful for separating a business thesis from dependence on the terminal value or a narrow discount-rate choice. The committee compares the valuation implications with the expectations plausibly embedded in the market price, using the same dated quotation basis as the workbook. A large modeled upside is not automatically a margin of safety if it depends on an unproved terminal state. The investment case becomes stronger when it remains acceptable under a range of defensible inputs and when the required operational improvements can be monitored through specific evidence. [src: synthetic_archive]
"""),
"portfolio_risk": ("Risk, liquidity and the real portfolio", """
Standalone attractiveness and portfolio suitability are related but distinct questions. The fictional company's exposure to industrial demand, capital spending and customer inventories may overlap with risks already present in a real portfolio. Adding an apparently different ticker can therefore increase concentration in the same economic driver. The committee reads the actual portfolio from its authorized database and uses it as context; it does not create a pretend portfolio consisting only of the candidate. If the book is unavailable or stale, the thesis can still be researched, but personalized sizing must remain unavailable rather than being reconstructed from memory. [src: synthetic_archive]

Risk is assessed through mechanisms as well as historical statistics. A stock with modest recent volatility may still be vulnerable to a discrete program loss or refinancing event. Conversely, a volatile quotation may reflect a temporary market dislocation without indicating equivalent deterioration in the business. The committee distinguishes price risk, fundamental uncertainty, liquidity and balance-sheet resilience. Historical drawdowns and correlations describe observed behavior under the available sample; they do not guarantee the next stress outcome. The research states the observation window and data limitations whenever those measures influence the proposed portfolio role. [src: synthetic_archive]

Liquidity analysis considers both normal trading conditions and the ability to adjust exposure when the thesis changes. Average turnover alone may hide a narrow free float, concentrated ownership or a tendency for spreads to widen around announcements. Position size should be assessed against executable liquidity, investment horizon and the risk of needing to trade at the same time as other investors. The committee avoids converting a broad statement that the stock is liquid into an exact recommended amount. Any operational proposal must be supported by the actual mandate, cash availability and quantitative controls that the application verifies independently of the model's confidence. [src: synthetic_archive]

The existing-position case requires particular care. A favorable view on a stock already held does not automatically justify adding exposure, and the application's action must reflect the actual book. Prior decisions and PM feedback may contain limits, objections or an explicit decision to wait. Those records are part of the investment context and cannot be overwritten by a fresh enthusiastic memo. Recent trades can also change the meaning of a proposal: a recommendation to buy may already have been executed, or a reduction may have altered the risk balance. The committee reviews the dated records and explains how they affect the current recommendation. [src: synthetic_archive]

The resulting portfolio conclusion is conditional on verified constraints. A thesis can pass economic review while remaining in research because the proposed amount lacks a defensible basis or the book changed during the run. This is a useful distinction, not a failure to decide. It preserves the investment work while preventing an unsupported operational instruction from appearing as ready to execute. The workflow records the specific obstacle and the evidence needed to reopen it. No order is sent automatically, and neither a favorable judgment nor a successful PDF/email delivery changes the PM's authority over the final trade decision. [src: synthetic_archive]
"""),
"catalysts": ("Catalysts, macro conditions and event risk", """
A catalyst is useful only when there is a credible connection between an observable event and the unresolved investment question. For the fictional supplier, a customer program renewal may reveal more about pricing power than a general industry conference. An earnings release may clarify cash conversion if it includes the relevant balance-sheet bridge, but it may add little if it merely repeats a broad demand assessment. The committee identifies the information expected from each event and the conditions under which it would change the thesis. A calendar entry without an analytical link is monitoring activity, not a catalyst argument. [src: synthetic_archive]

The macro analysis focuses on the channels that matter for the candidate. Industrial customers may delay equipment orders when financing costs rise, while currency changes can affect both reported revenue and the economics of imported inputs. Energy or freight costs may influence gross margins with different lags depending on contract terms. These relationships are not assumed to be uniform across the business. The committee asks which segments carry the exposure, whether hedging or pass-through provisions exist, and how quickly customer behavior responds. Broad forecasts for economic growth are context, not a substitute for that transmission analysis. [src: synthetic_archive]

Political and regulatory developments can matter through market access, certification requirements, tariffs, procurement rules or restrictions on technology transfer. The research separates enacted rules from proposals and speculation. It also distinguishes a company's ability to comply from its ability to recover the associated cost through pricing. A regulation that raises qualification barriers may strengthen incumbency while simultaneously increasing investment needs. The net effect cannot be inferred from the headline alone. Where the relevant legal or regulatory source has not been verified, the report states that limitation and avoids presenting a speculative interpretation as a settled financial fact. [src: synthetic_archive]

The news review tests whether recent announcements represent new information or repetitions of an existing narrative. Customer wins can be economically material, but their value depends on scope, duration, exclusivity and the investment required to deliver them. Management changes may affect capital allocation, yet a new executive's biography does not establish an improvement in future returns. The committee prioritizes original releases, filings and attributable statements, records acquisition dates, and retains uncertainty where reporting is indirect. It does not convert a large number of similar headlines into stronger evidence merely because the story appears frequently. [src: synthetic_archive]

The monitoring plan connects each material catalyst to a decision rule. Favorable evidence would include program economics that preserve returns after investment and cash collection consistent with reported sales. Adverse evidence would include cancelled launches, concessions at renewal or a buildup of balances that cannot be reconciled to normal operations. The research also records what would make the catalyst thesis stale, such as a postponed event or a change in the information expected from it. This keeps the pipeline useful after the report is issued: a dated condition can be revisited, while a generic instruction to watch the news cannot guide a disciplined update. [src: synthetic_archive]
"""),
"positioning": ("Options, positioning and secondary exposures", """
Options can add information about the distribution of market expectations, but the analysis depends on contract identity, timestamp, liquidity and the construction of the observed surface. A quoted implied volatility is not a direct forecast of realized volatility, and a large open-interest figure does not identify the economic motivation of its holders. For the fictional candidate, the committee treats options as a potential cross-check on event pricing and downside protection rather than as an automatic trading recommendation. Where the relevant chain is unavailable or insufficiently liquid, it says so and avoids manufacturing a strategy from incomplete quotes. [src: synthetic_archive]

The useful comparison is between the risk implied by traded contracts and the uncertainty identified by the fundamental analysis. If an upcoming event could materially change the investment case, the committee examines whether options appear to price unusually large movement around that date, while recognizing that spreads and stale quotes may distort the signal. It would compare like-for-like maturities, strikes and contract specifications, preserve units and avoid confusing absolute option premium with a percentage of the underlying. A strategy would require a separate assessment of payoff, financing, execution and mandate compatibility; a research observation alone is not an executable options order. [src: synthetic_archive]

Positioning evidence from ownership, short interest or trading activity also requires careful interpretation. A concentrated shareholder register can support patient ownership but reduce available liquidity. Reported short interest may reflect directional skepticism, hedging or other exposures that are not visible in the aggregate statistic. Changes in ownership data can be delayed relative to the market event being analyzed. The committee therefore asks whether the positioning information is timely, complete and relevant to the proposed catalyst. It does not infer that a crowded position must reverse or that a contrarian label makes the investment attractive. [src: synthetic_archive]

Crypto-related exposure is immaterial in this synthetic manufacturing case unless the business holds relevant assets, depends on crypto-linked demand or has financing arrangements that create such a connection. The Crypto desk still participates and documents the basis for non-applicability. This preserves the domain review without inventing token exposure to fill a page. The space is used to examine a more relevant secondary risk: whether customer financing or speculative end-market investment could amplify the supplier's order cycle. The distinction keeps the committee comprehensive while allowing each specialist to state honestly when its usual metrics do not apply. [src: synthetic_archive]

The integrated conclusion is that positioning and derivatives evidence can refine timing and risk management but should not displace the operating thesis. A superficially attractive options payoff does not cure an unresolved accounting bridge, and apparent investor pessimism does not prove that the market misunderstands the business. The committee records any material disagreement between market-implied expectations and its own scenarios, together with the data limitations. It also specifies what further evidence would make the discrepancy actionable. Until then, the analysis remains a documented research input, with no unsupported probability, hidden proxy or automatic execution attached to it. [src: synthetic_archive]
"""),
"red_team": ("Red Team challenge and unresolved objections", """
The Red Team's strongest objection is that the apparent franchise may be a collection of temporary customer dependencies rather than a durable source of excess returns. Incumbency is valuable during a program, but the supplier may have to surrender much of that value to win the next one. The investment thesis would be overstated if it capitalized current retention without accounting for future concessions and development requirements. The Capo accepts this objection as material. Its response is to demand renewal-cohort economics and to keep the upside case conditional on evidence of value capture after the full cost of remaining qualified. [src: synthetic_archive]

A second objection challenges cash conversion. The favorable earnings narrative may reflect utilization and shipment timing while inventory and receivables absorb the cash. If those balances do not reverse as programs mature, the business could be less capital-efficient than the headline margin suggests. The response is not to assume a convenient release of working capital in the forecast. It is to reconcile each relevant balance, identify its operating purpose and examine subsequent collections or consumption where available. The committee retains an explicit gap where the synthetic archive lacks the information needed to distinguish temporary timing from a structural funding requirement. [src: synthetic_archive]

The Red Team also questions the selection of comparable companies. High-quality peers may have proprietary products, recurring service revenue or stronger intellectual-property rights that the candidate does not possess. Applying their multiples would import economics that have not been established. The Capo addresses this by treating peer valuation as a conditional cross-check after business-model and accounting reconciliation. The principal valuation remains tied to the candidate's own operating drivers and claim structure. Any premium attributed to quality must be explained through expected returns and duration, rather than justified by a peer label or an attractive presentation. [src: synthetic_archive]

Another challenge concerns the PM's role in the process. A strongly expressed initial view can influence which evidence is gathered and which objections receive attention. The committee responds by preserving the original view separately, asking every specialist to test it, and requiring the Capo to state explicit disagreement where the evidence warrants it. This does not remove all analytical bias, but it makes the reasoning reviewable. The final judgment cannot be inferred from the PM's preference, the number of supportive desk reports or the mere existence of a completed valuation. The record must show the evidence that supports the conclusion and the objections that remain unresolved. [src: synthetic_archive]

The unresolved issue is the durability of program economics through a full renewal cycle. Available synthetic evidence can illustrate the investment mechanisms and support a conditional valuation, but it cannot establish that every customer cohort will behave similarly. The committee therefore defines invalidation conditions rather than declaring the risk eliminated. Persistent concessions, unrecovered development spending or deterioration in cash conversion would weaken the thesis even if reported sales continued to grow. Favorable renewals with adequate returns and clean cash conversion would strengthen it. These conditions preserve the substance of the adversarial review in the decision and make future reassessment more disciplined than a vague promise to remain vigilant. [src: synthetic_archive]
"""),
"decision": ("Decision, implementation conditions and review path", """
The Capo's conclusion follows the evidence and the operational checks independently. A favorable analytical judgment means that the expected business economics appear attractive under the stated assumptions; it does not mean that every portfolio can act immediately. The application verifies the selected ticker, the actual position, the mandate, relevant feedback and the proposed amount before routing an operational decision. When any of those requirements is incomplete, the research is preserved with an explicit reason and a condition for reassessment. This prevents a persuasive memo from becoming a trade instruction merely because it contains an action word. [src: synthetic_archive]

For a rejected thesis, the decision record must explain why the evidence does not justify investment. It should distinguish a weak business, an unattractive price, an unsupported analytical premise and a portfolio constraint, because those conditions have different implications for future work. A rejection based on price may be revisited when the market changes; a rejection based on accounting uncertainty requires new evidence rather than a cheaper quote. The report does not soften a negative conclusion into a promising opportunity for politeness. It preserves the strongest positive argument while stating clearly which adverse facts or unresolved risks dominate the decision. [src: synthetic_archive]

For an incomplete thesis, the next step is defined by the missing evidence. A broad instruction to do more research is insufficient. The committee identifies the specific reconciliation, source, contract detail or portfolio input that would permit the analysis to advance. It also records whether the gap blocks valuation, implementation or both. This distinction matters because a valid workbook may already exist even when a personal allocation decision cannot be made. Conversely, a coherent qualitative thesis does not justify inventing numerical assumptions to create a workbook. The incomplete component remains visible in the application, PDF and email with the same explanation. [src: synthetic_archive]

The review path preserves history. A later run may reuse the prior view as a starting point, but it creates a new dated assessment rather than rewriting the original research or the PM's feedback. Changes in conclusion should be attributable to new evidence, different assumptions or altered portfolio constraints. The record retains the earlier report and the linked artifact identities so that the evolution of the thesis can be examined. Technical retries have a different meaning: retrying a failed email sends the same validated package and does not create a new investment decision or trigger another paid committee analysis. [src: synthetic_archive]

The final monitoring conditions focus on the economically decisive observations: renewal returns after development investment, cash conversion through the production cycle, classification of mixed balance-sheet items and evidence of sustainable value capture. The PM retains responsibility for deciding whether and when to trade. A successful research run is demonstrated by a traceable conclusion, preserved dissent, a usable or explicitly incomplete model and a correctly delivered package. It is not demonstrated by investment performance that has not yet occurred. This synthetic dossier tests that separation and the product's ability to carry the same judgment consistently from the committee through persistence, interface, report and email. [src: synthetic_archive]
"""),
}


def research_result(judgment="favorable", *, run_id="11111111-1111-4111-8111-111111111111"):
    sections = [{"key": key, "title": title, "paragraphs": [p.strip() for p in prose.strip().split("\n\n")],
                 "evidence_ids": ["archive"], "tables": [], "charts": []}
                for key, (title, prose) in TEXT.items()]
    sections[5]["tables"] = [{"title": "Synthetic sensitivity illustration", "columns": ["Scenario", "Illustrative index"],
        "rows": [["Downside", "80"], ["Central", "100"], ["Upside", "125"]],
        "source": "synthetic_archive; assumptions for renderer replay only", "unit": "Index points (hypothetical)",
        "period": "Synthetic scenario horizon"}]
    sections[5]["charts"] = [{"table_index": 0, "kind": "bar", "label_column": 0, "value_columns": [1]}]
    data = {"ticker": "SYNTH-EXT", "judgment": judgment,
        "summary": {"favorable": "Conditional favorable synthetic thesis; independent portfolio checks still apply.",
                    "rejected": "Rejected synthetic thesis: the evidence does not support durable value capture.",
                    "incomplete": "Research concluded with economic gaps: the capital bridge lacks evidence.",
                    "watch": "Monitor renewals and cash conversion before revisiting the synthetic thesis."}[judgment],
        "pm_view_response": "The claim of complete protection against a downturn is contradicted by renewal and cash-conversion risks.",
        "pros": ["Qualification supports retention within an established program."],
        "cons": ["Retention does not establish pricing power at renewal."],
        "risks": ["Cash conversion can deteriorate before reported earnings."],
        "catalysts": ["A program renewal with documented investment returns."],
        "invalidation": ["Persistent concessions and unrecovered development spending."],
        "data_gaps": ["Cash bridge needs qualification."] if judgment == "incomplete" else [],
        "review_conditions": ["Verify renewal-cohort economics and subsequent cash collection."],
        "scenarios": [{"name": "Central", "analysis": "Existing programs convert with continuing reinvestment.", "evidence_ids": ["archive"]}],
        "objections": [{"objection": "Incumbency may be temporary.", "response": "Require renewal-cohort evidence.",
                        "resolved": False, "evidence_ids": ["archive"]}],
        "history_review": [], "evidence": [{"id": "archive", "source": "synthetic_archive",
            "as_of": "2026-09-10", "summary": "Entirely fictional provider replay for software verification.", "url": "https://example.org/synthetic-research"}],
        "dossier": sections, "proposal": {"ticker": "SYNTH-EXT", "action": "BUY", "eur_amount": None,
            "timing": "After independent checks", "confidence": "MEDIA", "rationale": "Synthetic conditional thesis",
            "sizing_source": None} if judgment == "favorable" else None}
    result = validate_result(data, run_id=run_id, ticker="SYNTH-EXT", pm_view="Switching costs make this business immune to a downturn.")
    result["destination"] = {"kind": "research", "reason": "Offline fixture; no personal allocation."}
    return result


def run_record(run_id="11111111-1111-4111-8111-111111111111"):
    return {"id": run_id, "ticker": "SYNTH-EXT", "started_at": "2026-09-10T12:00:00Z",
            "cutoff": "2026-09-10T12:00:00Z", "identity": {"name": "Synthetic Components - offline fixture",
            "exchange": "Synthetic exchange", "currency": "EUR"},
            "models": {"specialists": "simulated Muse provider", "capo": "simulated Opus provider"}}


def bind_workbook(result, workbook):
    """Provider-fixture reference to the exact common-engine generation it saw."""
    result["valuation_refs"] = [{key: workbook[key] for key in
                                  ("snapshot_id", "generation_id", "valuation_date")} | {
        "interpretation": "Synthetic replay reviewed these exact documented assumptions at the stated historical cutoff; this is not a live investment valuation."}]
    return result
