import { linguaCorrente, type Lingua } from '@/i18n/lingua';
import { traduci, type Chiave, type Parametri } from '@/i18n/t';
import type { FilingGruppoUi, FilingStatoUi } from '@/lib/api';

// I testi stanno nel catalogo (i18n/it|en/filingPage.ts): qui solo la forma che le viste usano.
function costruisci(l: Lingua) {
  const tr = (k: Chiave, p?: Record<string, string | number | null | undefined>) => traduci(l, k, p as Parametri | undefined);
  return {
    title: tr('filingPage.title'),
    scope: tr('filingPage.scope'),
    portfolio: tr('filingPage.portfolio'),
    favorites: tr('filingPage.favorites'),
    covered: (_n: number, tot: number) => tr('filingPage.covered', { tot }),
    coveredN: (n: number) => String(n),
    checkedAt: (quando: string) => tr('filingPage.checkedAt', { quando }),
    checkRunning: tr('filingPage.checkRunning'),
    checkNever: tr('filingPage.checkNever'),
    daily: tr('filingPage.daily'),
    dailyHint: tr('filingPage.dailyHint'),
    dailyForced: tr('filingPage.dailyForced'),
    review: (n: number) => n === 1 ? tr('filingPage.review_one') : tr('filingPage.review_other', { n }),
    activateMissing: tr('filingPage.activateMissing'),
    activatingMissing: tr('filingPage.activatingMissing'),
    activateMissingHint: tr('filingPage.activateMissingHint'),
    activateMissingFav: tr('filingPage.activateMissingFav'),
    bulkResult: (a: number, c: number, s: number) => a === 1 ? tr('filingPage.bulkResult_one', { c, s }) : tr('filingPage.bulkResult_other', { a, c, s }),
    bulkFirst: tr('filingPage.bulkFirst'),
    bulkQueued: tr('filingPage.bulkQueued'),
    bulkDone: tr('filingPage.bulkDone'),
    bulkErrors: (n: number) => n === 1 ? tr('filingPage.bulkErrors_one') : tr('filingPage.bulkErrors_other', { n }),
    close: tr('filingPage.close'),
    ctxTitle: tr('filingPage.ctxTitle'),
    ctxGloss: tr('filingPage.ctxGloss'),
    ctxGlossFav: tr('filingPage.ctxGlossFav'),
    ctxFresh: (_n: number) => tr('filingPage.ctxFresh'),
    ctxStale: (_n: number) => tr('filingPage.ctxStale'),
    ctxConfirm: (n: number): string => n === 1 ? tr('filingPage.ctxConfirm_one') : tr('filingPage.ctxConfirm_other'),
    ctxNoSource: (_n: number) => tr('filingPage.ctxNoSource'),
    ctxExcluded: (n: number) => n === 1 ? tr('filingPage.ctxExcluded_one') : tr('filingPage.ctxExcluded_other', { n }),
    budget: tr('filingPage.budget'),
    budgetOf: (b: string) => tr('filingPage.budgetOf', { b }),
    budgetOmitted: (n: number) => n === 1 ? tr('filingPage.budgetOmitted_one') : tr('filingPage.budgetOmitted_other', { n }),
    list: tr('filingPage.list'),
    orderNew: tr('filingPage.orderNew'),
    orderAz: tr('filingPage.orderAz'),
    order: tr('filingPage.order'),
    groups: { novita: tr('filingPage.groups_novita'), da_sistemare: tr('filingPage.groups_da_sistemare'), aggiornati: tr('filingPage.groups_aggiornati'), senza_fonte: tr('filingPage.groups_senza_fonte') } as Record<FilingGruppoUi, string>,
    listFoot: tr('filingPage.listFoot'),
    listEmpty: tr('filingPage.listEmpty'),
    listEmptyFav: tr('filingPage.listEmptyFav'),
    nuovi: (n: number) => n === 1 ? tr('filingPage.nuovi_one') : tr('filingPage.nuovi_other', { n }),
    tag: { novita: tr('filingPage.tag_novita'), aggiornato: tr('filingPage.tag_aggiornato'), invariato: tr('filingPage.tag_invariato'), in_corso: tr('filingPage.tag_in_corso'), primo_confronto: tr('filingPage.tag_primo_confronto'), errore: tr('filingPage.tag_errore'), da_confermare: tr('filingPage.tag_da_confermare'), proposta_ai: tr('filingPage.tag_proposta_ai'), senza_fonte: tr('filingPage.tag_senza_fonte'), non_attivo: tr('filingPage.tag_non_attivo'), escluso: tr('filingPage.tag_escluso') } as Record<FilingStatoUi, string>,
    sub: {
      noSource: tr('filingPage.sub_noSource'), pdfFound: tr('filingPage.sub_pdfFound'),
      candidates: (n: number) => n === 1 ? tr('filingPage.sub_candidates_one') : tr('filingPage.sub_candidates_other', { n }),
      notActive: tr('filingPage.sub_notActive'), excluded: tr('filingPage.sub_excluded'), unlinked: tr('filingPage.sub_unlinked'), autoOff: tr('filingPage.sub_autoOff'),
    },
    today: tr('filingPage.today'),
    yesterday: tr('filingPage.yesterday'),
    now: tr('filingPage.now'),
    loading: tr('filingPage.loading'),
    readError: tr('filingPage.readError'),
    unavailable: tr('filingPage.unavailable'),
    retry: tr('filingPage.retry'),
    pick: tr('filingPage.pick'),
    source: tr('filingPage.source'),
    comparison: tr('filingPage.comparison'),
    run: tr('filingPage.run'),
    next: tr('filingPage.next'),
    freshness: tr('filingPage.freshness'),
    coverage: tr('filingPage.coverage'),
    lastOk: tr('filingPage.lastOk'),
    lastTry: tr('filingPage.lastTry'),
    outcome: tr('filingPage.outcome'),
    started: tr('filingPage.started'),
    trigger: tr('filingPage.trigger'),
    state: tr('filingPage.state'),
    search: tr('filingPage.search'),
    profile: tr('filingPage.profile'),
    cost: tr('filingPage.cost'),
    candidatesL: tr('filingPage.candidatesL'),
    consigliere: tr('filingPage.consigliere'),
    document: tr('filingPage.document'),
    proposal: tr('filingPage.proposal'),
    model: tr('filingPage.model'),
    tokens: tr('filingPage.tokens'),
    fresh: tr('filingPage.fresh'),
    stale: tr('filingPage.stale'),
    partial: tr('filingPage.partial'),
    free: tr('filingPage.free'),
    notCreated: tr('filingPage.notCreated'),
    missingDeclared: tr('filingPage.missingDeclared'),
    sections: (a: number, b: number) => tr('filingPage.sections', { a, b }),
    byName: tr('filingPage.byName'),
    toChoose: tr('filingPage.toChoose'),
    triggers: { manual: tr('filingPage.triggers_manual'), schedule: tr('filingPage.triggers_schedule'), scheduled: tr('filingPage.triggers_scheduled'), activation: tr('filingPage.triggers_activation'), prerun: tr('filingPage.triggers_prerun'), startup: tr('filingPage.triggers_startup') } as Record<string, string>,
    openProfile: tr('filingPage.openProfile'),
    closeProfile: tr('filingPage.closeProfile'),
    checkNow: tr('filingPage.checkNow'),
    checkNowAi: tr('filingPage.checkNowAi'),
    checkNowHint: tr('filingPage.checkNowHint'),
    checkNowAiHint: tr('filingPage.checkNowAiHint'),
    retryCheck: tr('filingPage.retryCheck'),
    retryCheckAi: tr('filingPage.retryCheckAi'),
    unverifiedLatest: tr('filingPage.unverifiedLatest'),
    pill: { in_corso: tr('filingPage.pill_in_corso'), da_confermare: tr('filingPage.pill_da_confermare'), proposta_ai: tr('filingPage.pill_proposta_ai'), non_attivo: tr('filingPage.pill_non_attivo'), escluso: tr('filingPage.pill_escluso'), senza_fonte: tr('filingPage.pill_senza_fonte') } as Partial<Record<FilingStatoUi, string>>,
    aiInterim: tr('filingPage.aiInterim'),
    aiInterimHint: tr('filingPage.aiInterimHint'),
    changes: tr('filingPage.changes'),
    changesIfrs: tr('filingPage.changesIfrs'),
    filters: tr('filingPage.filters'),
    fHighlight: tr('filingPage.fHighlight'),
    fRisks: tr('filingPage.fRisks'),
    fMgmt: tr('filingPage.fMgmt'),
    fLegal: tr('filingPage.fLegal'),
    fAll: tr('filingPage.fAll'),
    kind: { aggiunto: tr('filingPage.kind_aggiunto'), rimosso: tr('filingPage.kind_rimosso'), modificato: tr('filingPage.kind_modificato'), spostato: tr('filingPage.kind_spostato') } as Record<string, string>,
    openDoc: tr('filingPage.openDoc'),
    changesFoot: tr('filingPage.changesFoot'),
    changesFootHighlight: tr('filingPage.changesFootHighlight'),
    noChanges: tr('filingPage.noChanges'),
    noChangesFilter: tr('filingPage.noChangesFilter'),
    noComparison: tr('filingPage.noComparison'),
    waitingFirst: tr('filingPage.waitingFirst'),
    shownOf: (a: number, b: number) => tr('filingPage.shownOf', { a, b }),
    showMore: (n: number) => tr('filingPage.showMore', { n }),
    noPair: (m: string) => tr('filingPage.noPair', { m }),
    noPairTag: tr('filingPage.noPairTag'),
    tables: (n: number) => n === 1 ? tr('filingPage.tables_one') : tr('filingPage.tables_other', { n }),
    tablesHint: tr('filingPage.tablesHint'),
    showTables: tr('filingPage.showTables'),
    hideTables: tr('filingPage.hideTables'),
    listNumbers: (n: number) => n === 1 ? tr('filingPage.listNumbers_one') : tr('filingPage.listNumbers_other', { n }),
    partialEsef: tr('filingPage.partialEsef'),
    historical: tr('filingPage.historical'),
    lightCheck: (q: string) => tr('filingPage.lightCheck', { q }),
    unpaired: tr('filingPage.unpaired'),
    figures: tr('filingPage.figures'),
    figVoce: { ricavi: tr('filingPage.figVoce_ricavi'), utile_operativo: tr('filingPage.figVoce_utile_operativo'), utile_netto: tr('filingPage.figVoce_utile_netto'), scorte: tr('filingPage.figVoce_scorte'), debito: tr('filingPage.figVoce_debito'), flusso_cassa_operativo: tr('filingPage.figVoce_flusso_cassa_operativo'), margine_lordo: tr('filingPage.figVoce_margine_lordo') } as Record<string, string>,
    figVariant: (v: string) => tr('filingPage.figVariant', { v }),
    figPeriodo: { annuale: tr('filingPage.figPeriodo_annuale'), semestrale: tr('filingPage.figPeriodo_semestrale'), trimestrale: tr('filingPage.figPeriodo_trimestrale'), nove_mesi: tr('filingPage.figPeriodo_nove_mesi') } as Record<string, string>,
    figSource: (f: string, valuta: string, qoq = false) => tr('filingPage.figSource', { f: valuta ? `${f} · ${valuta}` : f, base: qoq ? tr('filingPage.figSource_qoq') : tr('filingPage.figSource_yoy') }),
    figAfterFirst: tr('filingPage.figAfterFirst'),
    figNone: tr('filingPage.figNone'),
    figIr: tr('filingPage.figIr'),
    figNoData: tr('filingPage.figNoData'),
    figLast: tr('filingPage.figLast'),
    cons: tr('filingPage.cons'),
    copy: tr('filingPage.copy'),
    copied: tr('filingPage.copied'),
    consCharsL: tr('filingPage.consCharsL'),
    consChangesL: (b: number) => tr('filingPage.consChangesL', { b }),
    consFiguresL: (n: number): string => n === 1 ? tr('filingPage.consFiguresL_one') : tr('filingPage.consFiguresL_other'),
    consCites: tr('filingPage.consCites'),
    consOmitted: (n: number) => tr('filingPage.consOmitted', { n }),
    consFoot: tr('filingPage.consFoot'),
    consFootMissing: tr('filingPage.consFootMissing'),
    consFootStale: tr('filingPage.consFootStale'),
    consFootAi: tr('filingPage.consFootAi'),
    consNotIn: tr('filingPage.consNotIn'),
    consError: tr('filingPage.consError'),
    listingError: (e: string) => tr('filingPage.listingError', { e }),
    detailError: (e: string) => tr('filingPage.detailError', { e }),
    consPrevious: tr('filingPage.consPrevious'),
    runTitle: tr('filingPage.runTitle'),
    runStarted: (h: string, t: string) => tr('filingPage.runStarted', { h, t }),
    runWorking: tr('filingPage.runWorking'),
    runNote: tr('filingPage.runNote'),
    runFoot: tr('filingPage.runFoot'),
    errTitle: tr('filingPage.errTitle'),
    errWhat: tr('filingPage.errWhat'),
    errProfile: tr('filingPage.errProfile'),
    errRetry: tr('filingPage.errRetry'),
    errOcr: tr('filingPage.errOcr'),
    errGeneric: tr('filingPage.errGeneric'),
    errProfileBtn: tr('filingPage.errProfileBtn'),
    errFoot: (d: string) => tr('filingPage.errFoot', { d }),
    errFootNone: tr('filingPage.errFootNone'),
    errDoc: tr('filingPage.errDoc'),
    errFound: tr('filingPage.errFound'),
    errMissing: tr('filingPage.errMissing'),
    linkTitle: tr('filingPage.linkTitle'),
    linkSec: tr('filingPage.linkSec'),
    linkEsef: tr('filingPage.linkEsef'),
    linkOne: tr('filingPage.linkOne'),
    linkSearching: tr('filingPage.linkSearching'),
    linkError: (e: string) => tr('filingPage.linkError', { e }),
    confirm: tr('filingPage.confirm'),
    activating: tr('filingPage.activating'),
    none: tr('filingPage.none'),
    noneHint: tr('filingPage.noneHint'),
    linkFoot: (t: string) => tr('filingPage.linkFoot', { t }),
    sameName: tr('filingPage.sameName'),
    similar: tr('filingPage.similar'),
    alias: tr('filingPage.alias'),
    ticker: tr('filingPage.ticker'),
    offTitle: tr('filingPage.offTitle'),
    offText: tr('filingPage.offText'),
    offSec: tr('filingPage.offSec'),
    offEsef: tr('filingPage.offEsef'),
    offIr: tr('filingPage.offIr'),
    offIrNone: tr('filingPage.offIrNone'),
    offNotTried: tr('filingPage.offNotTried'),
    search_: tr('filingPage.search_'),
    indicateIr: tr('filingPage.indicateIr'),
    manual: tr('filingPage.manual'),
    exclude: tr('filingPage.exclude'),
    include: tr('filingPage.include'),
    manualLabel: tr('filingPage.manualLabel'),
    manualGo: tr('filingPage.manualGo'),
    manualInvalid: tr('filingPage.manualInvalid'),
    offFoot: tr('filingPage.offFoot'),
    pdfTitle: tr('filingPage.pdfTitle'),
    pdfText: (sito: string) => tr('filingPage.pdfText', { sito }),
    pdfLatest: tr('filingPage.pdfLatest'),
    pdfPrevious: tr('filingPage.pdfPrevious'),
    pdfNoPrevious: tr('filingPage.pdfNoPrevious'),
    pdfEstimate: tr('filingPage.pdfEstimate'),
    pdfSearch: tr('filingPage.pdfSearch'),
    pdfSearching: tr('filingPage.pdfSearching'),
    pdfNone: tr('filingPage.pdfNone'),
    pdfAt: (q: string) => tr('filingPage.pdfAt', { q }),
    pdfTipo: { annuale: tr('filingPage.pdfTipo_annuale'), semestrale: tr('filingPage.pdfTipo_semestrale'), trimestrale: tr('filingPage.pdfTipo_trimestrale') } as Record<string, string>,
    offIrFound: (n: number) => n === 1 ? tr('filingPage.offIrFound_one') : tr('filingPage.offIrFound_other', { n }),
    sOneClick: tr('filingPage.sOneClick'),
    exclTitle: tr('filingPage.exclTitle'),
    exclText: tr('filingPage.exclText'),
    activated: tr('filingPage.activated'),
    rejected: tr('filingPage.rejected'),
    excludedOk: tr('filingPage.excludedOk'),
    includedOk: tr('filingPage.includedOk'),
    queued: tr('filingPage.queued'),
    actionError: (e: string) => tr('filingPage.actionError', { e }),
    aiTitle: tr('filingPage.aiTitle'),
    aiIntro: tr('filingPage.aiIntro'),
    aiUrl: tr('filingPage.aiUrl'),
    aiOthers: tr('filingPage.aiOthers'),
    aiEstimate: tr('filingPage.aiEstimate'),
    aiEstimating: tr('filingPage.aiEstimating'),
    aiPropose: (c: string) => tr('filingPage.aiPropose', { c }),
    aiProposeCached: tr('filingPage.aiProposeCached'),
    aiProposing: tr('filingPage.aiProposing'),
    aiEstimateLine: (p: number, tok: string, c: string) => tr('filingPage.aiEstimateLine', { p, tok, c }),
    aiCached: tr('filingPage.aiCached'),
    aiTruncated: (n: number) => tr('filingPage.aiTruncated', { n }),
    aiNotConfigured: (v: string) => tr('filingPage.aiNotConfigured', { v }),
    aiFound: (p: string) => tr('filingPage.aiFound', { p }),
    aiFoundNoPage: tr('filingPage.aiFoundNoPage'),
    aiFromTo: (a: string, b: string) => tr('filingPage.aiFromTo', { a, b }),
    aiWarnings: tr('filingPage.aiWarnings'),
    aiOthersCheck: (n: string) => tr('filingPage.aiOthersCheck', { n }),
    aiSave: (n: number) => n === 1 ? tr('filingPage.aiSave_one') : tr('filingPage.aiSave_other', { n }),
    aiAddVariant: (tipo: string) => tr('filingPage.aiAddVariant', { tipo }),
    aiReplace: tr('filingPage.aiReplace'),
    aiReplaceConfirm: tr('filingPage.aiReplaceConfirm'),
    aiDiscard: tr('filingPage.aiDiscard'),
    aiRetry: tr('filingPage.aiRetry'),
    aiRetryHint: tr('filingPage.aiRetryHint'),
    aiNothing: tr('filingPage.aiNothing'),
    aiSaved: tr('filingPage.aiSaved'),
    aiVariantAdded: (t: string) => tr('filingPage.aiVariantAdded', { t }),
    aiDiscarded: tr('filingPage.aiDiscarded'),
    aiStale: tr('filingPage.aiStale'),
    aiCost: (c: string) => tr('filingPage.aiCost', { c }),
    aiFoot: tr('filingPage.aiFoot'),
    aiError: (e: string) => tr('filingPage.aiError', { e }),
    aiInProgress: (s: string) => tr('filingPage.aiInProgress', { s }),
    aiSecondsNd: tr('filingPage.aiSecondsNd'),
    aiRefused: (motivo: string) => tr('filingPage.aiRefused', { motivo }),
    aiReasonMissing: tr('filingPage.aiReasonMissing'),
    aiJobLost: tr('filingPage.aiJobLost'),
    aiRefusedVar: (v: string) => tr('filingPage.aiRefusedVar', { v }),
    aiRetryIn: (s: string) => tr('filingPage.aiRetryIn', { s }),
    aiUnreachable: tr('filingPage.aiUnreachable'),
    aiTimeout: (min: string) => tr('filingPage.aiTimeout', { min }),
    aiRetryFree: tr('filingPage.aiRetryFree'),
    aiRetryFreeHint: tr('filingPage.aiRetryFreeHint'),
    aiClose: tr('filingPage.aiClose'),
    aiOtherPdf: tr('filingPage.aiOtherPdf'),
    aiVerifiedOf: (a: number, b: number) => tr('filingPage.aiVerifiedOf', { a, b }),
    aiVerifiedL: tr('filingPage.aiVerifiedL'),
    aiSemestrale: tr('filingPage.aiSemestrale'),
    aiTrimestrale: tr('filingPage.aiTrimestrale'),
    advTitle: tr('filingPage.advTitle'),
    advHelp: tr('filingPage.advHelp'),
    advJson: tr('filingPage.advJson'),
    advAuto: tr('filingPage.advAuto'),
    advInterval: tr('filingPage.advInterval'),
    advQual: tr('filingPage.advQual'),
    advSave: tr('filingPage.advSave'),
    advSaving: tr('filingPage.advSaving'),
    advSaved: tr('filingPage.advSaved'),
    advInvalidJson: tr('filingPage.advInvalidJson'),
    advInvalidInterval: tr('filingPage.advInvalidInterval'),
    advNone: tr('filingPage.advNone'),
    advHistory: tr('filingPage.advHistory'),
    advNoRuns: tr('filingPage.advNoRuns'),
    advLight: tr('filingPage.advLight'),
    advRun: tr('filingPage.advRun'),
    advPair: tr('filingPage.advPair'),
    advBefore: tr('filingPage.advBefore'),
    advAfter: tr('filingPage.advAfter'),
    advCandidates: tr('filingPage.advCandidates'),
    advCoverage: tr('filingPage.advCoverage'),
    advFresh: tr('filingPage.advFresh'),
    advPeriod: tr('filingPage.advPeriod'),
    advNextReport: tr('filingPage.advNextReport'),
    advJudgment: tr('filingPage.advJudgment'),
    advJudgmentNone: tr('filingPage.advJudgmentNone'),
    advCitations: tr('filingPage.advCitations'),
    advCitationMissing: tr('filingPage.advCitationMissing'),
    advIndex: tr('filingPage.advIndex'),
    advSources: tr('filingPage.advSources'),
    advDiff: tr('filingPage.advDiff'),
    advSections: tr('filingPage.advSections'),
    advSimilarity: tr('filingPage.advSimilarity'),
    advNotJudgment: tr('filingPage.advNotJudgment'),
    advCosine: tr('filingPage.advCosine'),
    advUncomparable: tr('filingPage.advUncomparable'),
    citeHint: (sha: string, pos: string) => tr('filingPage.citeHint', { sha, pos }),
    advUnlink: tr('filingPage.advUnlink'),
    advUnlinkConfirm: tr('filingPage.advUnlinkConfirm'),
    advUnlinked: tr('filingPage.advUnlinked'),
    advExclude: tr('filingPage.advExclude'),
    cancel: tr('filingPage.cancel'),
    yes: tr('filingPage.yes'),
    newChip: (_n: number) => tr('filingPage.newChip'),
    fixTitle: tr('filingPage.fixTitle'),
    fixReview: tr('filingPage.fixReview'),
    fixWhy: { errore: tr('filingPage.fixWhy_errore'), da_confermare: tr('filingPage.fixWhy_da_confermare'), proposta_ai: tr('filingPage.fixWhy_proposta_ai') } as Partial<Record<FilingStatoUi, string>>,
    fixMore: (n: number) => n === 1 ? tr('filingPage.fixMore_one') : tr('filingPage.fixMore_other', { n }),
    tFresh: tr('filingPage.tFresh'),
    tStale: tr('filingPage.tStale'),
    tConfirm: tr('filingPage.tConfirm'),
    tNoSource: tr('filingPage.tNoSource'),
    tFreshS: tr('filingPage.tFreshS'),
    tStaleS: tr('filingPage.tStaleS'),
    tConfirmS: tr('filingPage.tConfirmS'),
    tNoSourceS: tr('filingPage.tNoSourceS'),
    tExcludedS: (n: number) => n === 1 ? tr('filingPage.tExcludedS_one') : tr('filingPage.tExcludedS_other', { n }),
    budgetNote: tr('filingPage.budgetNote'),
    budgetLine: (b: string, n: number) => n === 1 ? tr('filingPage.budgetLine_one', { b }) : tr('filingPage.budgetLine_other', { b, n }),
    listNote: (n: number, az: boolean) => tr(az ? 'filingPage.listNote_az' : 'filingPage.listNote', { n }),
    sNext: (q: string) => tr('filingPage.sNext', { q }),
    sRun: (q: string) => tr('filingPage.sRun', { q }),
    sOf: (q: string) => tr('filingPage.sOf', { q }),
    sFresh: tr('filingPage.sFresh'),
    sStale: tr('filingPage.sStale'),
    sWaitFirst: tr('filingPage.sWaitFirst'),
    sFreeNoAi: tr('filingPage.sFreeNoAi'),
    sTry: (q: string) => tr('filingPage.sTry', { q }),
    sPublicList: tr('filingPage.sPublicList'),
    sCandidates: tr('filingPage.sCandidates'),
    sNoAi: tr('filingPage.sNoAi'),
    sInRow: tr('filingPage.sInRow'),
    sOneCall: tr('filingPage.sOneCall'),
    sLedger: tr('filingPage.sLedger'),
    sLocal: tr('filingPage.sLocal'),
    sNoMatch: tr('filingPage.sNoMatch'),
    sOnRequest: tr('filingPage.sOnRequest'),
    sChecking: tr('filingPage.sChecking'),
    changesNote: (n: number) => tr('filingPage.changesNote', { n }),
    figNoteSec: tr('filingPage.figNoteSec'),
    figNoteEsef: tr('filingPage.figNoteEsef'),
    figNoteQoq: tr('filingPage.figNoteQoq'),
    sQoq: tr('filingPage.sQoq'),
    qoqNote: tr('filingPage.qoqNote'),
    consNote: tr('filingPage.consNote'),
    aiNew: tr('filingPage.aiNew'),
    unknown: tr('filingPage.unknown'),
    aiSectionDiscarded: tr('filingPage.aiSectionDiscarded'),
    cifraBreve: (c: { testo: string; scala: 'bn' | 'mn' | 'k' | null } | null) => c == null ? '—' : c.scala === 'bn' ? tr('filingPage.num_bn', { x: c.testo }) : c.scala === 'mn' ? tr('filingPage.num_mn', { x: c.testo }) : c.scala === 'k' ? tr('filingPage.num_k', { x: c.testo }) : c.testo,
  };
}

type Parole = ReturnType<typeof costruisci>;
const cache = new Map<Lingua, Parole>();

export function parole(): Parole {
  const l = linguaCorrente();
  let d = cache.get(l);
  if (!d) { d = costruisci(l); cache.set(l, d); }
  return d;
}
export type { Parole };
