import { linguaCorrente, type Lingua } from '@/i18n/lingua';
import { traduci, type Chiave, type Parametri } from '@/i18n/t';
export type Parole = Dizionario;

// I testi stanno nel catalogo (i18n/it|en/newsPage.ts): qui solo la forma che le viste usano.
function costruisci(l: Lingua) {
  const tr = (k: Chiave, p?: Record<string, string | number | null | undefined>) => traduci(l, k, p as Parametri | undefined);
  return {
    title: tr('newsPage.title'),
    views: tr('newsPage.views'),
    viewFlow: tr('newsPage.viewFlow'),
    viewAgenda: tr('newsPage.viewAgenda'),
    inMemory: tr('newsPage.inMemory'),
    updatedAt: (h: string) => tr('newsPage.updatedAt', { h }),
    newSince: (n: number) => n === 1 ? tr('newsPage.newSince_one') : tr('newsPage.newSince_other', { n }),
    auto: tr('newsPage.auto'),
    autoHint: tr('newsPage.autoHint'),
    sources: tr('newsPage.sources'),
    pollProviders: tr('newsPage.pollProviders'),
    pollingProviders: tr('newsPage.pollingProviders'),
    pollHint: tr('newsPage.pollHint'),
    refreshAgenda: tr('newsPage.refreshAgenda'),
    refreshingAgenda: tr('newsPage.refreshingAgenda'),
    refreshResult: (saved: string, dup: string) => tr('newsPage.refreshResult', { saved, dup }),
    refreshJoinedDone: tr('newsPage.refreshJoinedDone'),
    refreshNotClassified: (n: string) => tr('newsPage.refreshNotClassified', { n }),
    coverage: tr('newsPage.coverage'),
    coverageMute: (list: string) => tr('newsPage.coverageMute', { list }),
    seeSources: tr('newsPage.seeSources'),
    // conteggi assenti = n.d. dichiarato (mai «0 nuove su 0»)
    roundChip: (h: string, nuove: number | null, lette: number | null) => nuove == null || lette == null
      ? tr('newsPage.roundChip_nd', { h, nuove: nuove ?? tr('newsPage.refreshTimeNd'), lette: lette ?? tr('newsPage.refreshTimeNd') })
      : tr(nuove === 1 ? 'newsPage.roundChip_one' : 'newsPage.roundChip_other', { h, nuove, lette }),
    roundChipNext: (h: string) => tr('newsPage.roundChipNext', { h }),
    roundChipHint: tr('newsPage.roundChipHint'),
    roundChipNone: tr('newsPage.roundChipNone'),
    budgetTitle: tr('newsPage.budgetTitle'),
    budgetUsed: (u: number, d: number) => tr('newsPage.budgetUsed', { u, d }),
    budgetPaced: (a: number, s: number, e: number) => tr('newsPage.budgetPaced', { a, s: String(s).padStart(2, '0'), e }),
    budgetNext: (h: string) => tr('newsPage.budgetNext', { h }),
    budgetFull: tr('newsPage.budgetFull'),
    budgetExplain: tr('newsPage.budgetExplain'),
    roundPartialNote: (list: string) => list ? tr('newsPage.roundPartialNote_list', { list }) : tr('newsPage.roundPartialNote'),
    pulse: tr('newsPage.pulse'),
    last24h: tr('newsPage.last24h'),
    positive: tr('newsPage.positive'),
    neutral: tr('newsPage.neutral'),
    negative: tr('newsPage.negative'),
    pulseAria: (n: number, peak: number, at: string) => tr('newsPage.pulseAria', { n, peak, at }),
    pulseEmpty: tr('newsPage.pulseEmpty'),
    peak: (n: number, at: string) => tr('newsPage.peak', { n, at }),
    now: tr('newsPage.now'),
    tipHour: (at: string, n: number) => n === 1 ? tr('newsPage.tipHour_one', { at }) : tr('newsPage.tipHour_other', { at, n }),
    radar: tr('newsPage.radar'),
    radarNote: tr('newsPage.radarNote'),
    radarAria: (n: number) => n === 1 ? tr('newsPage.radarAria_one') : tr('newsPage.radarAria_other', { n }),
    radarKeySize: tr('newsPage.radarKeySize'),
    radarKeyHot: tr('newsPage.radarKeyHot'),
    radarKeyFav: tr('newsPage.radarKeyFav'),
    radarHow: tr('newsPage.radarHow'),
    radarHowSector: tr('newsPage.radarHowSector'),
    radarHowDistance: tr('newsPage.radarHowDistance'),
    radarHowTone: tr('newsPage.radarHowTone'),
    radarHowHover: tr('newsPage.radarHowHover'),
    radarCount: (n: number) => n === 1 ? tr('newsPage.radarCount_one') : tr('newsPage.radarCount_other', { n }),
    radarDelta: (d: number, prev: number) => tr('newsPage.radarDelta', { d: `${d > 0 ? '+' : ''}${d}`, prev }),
    radarNoHistory: tr('newsPage.radarNoHistory'),
    radarTonePct: (p: number, n: number) => tr('newsPage.radarTonePct', { p, n }),
    radarLast: tr('newsPage.radarLast'),
    radarFilter: (t: string) => tr('newsPage.radarFilter', { t }),
    radarTone: (p: number, n: number) => tr('newsPage.radarTone', { p, n }),
    radarEmpty: tr('newsPage.radarEmpty'),
    search: tr('newsPage.search'),
    period: tr('newsPage.period'),
    periods: { today: tr('newsPage.periods_today'), "24h": tr('newsPage.periods_24h'), "3days": tr('newsPage.periods_3days'), week: tr('newsPage.periods_week'), all: tr('newsPage.periods_all') } as Record<string, string>,
    theme: tr('newsPage.theme'),
    ticker: tr('newsPage.ticker'),
    tone: tr('newsPage.tone'),
    relevance: tr('newsPage.relevance'),
    relevanceHint: tr('newsPage.relevanceHint'),
    relAll: tr('newsPage.relAll'),
    favOnly: tr('newsPage.favOnly'),
    favNone: tr('newsPage.favNone'),
    countOf: (a: number, b: number) => tr('newsPage.countOf', { a, b }),
    reset: tr('newsPage.reset'),
    flow: tr('newsPage.flow'),
    flowNote: tr('newsPage.flowNote'),
    today: tr('newsPage.today'),
    yesterday: tr('newsPage.yesterday'),
    undated: tr('newsPage.undated'),
    ofPortfolio: (w: string) => tr('newsPage.ofPortfolio', { w }),
    relOf: (r: number) => tr('newsPage.relOf', { r }),
    seen: (h: string) => tr('newsPage.seen', { h }),
    loading: tr('newsPage.loading'),
    feedEmpty: tr('newsPage.feedEmpty'),
    feedEmptyHint: tr('newsPage.feedEmptyHint'),
    noMatch: tr('newsPage.noMatch'),
    noMatchHint: tr('newsPage.noMatchHint'),
    retry: tr('newsPage.retry'),
    noSelection: tr('newsPage.noSelection'),
    noSelectionHint: tr('newsPage.noSelectionHint'),
    contextNews: tr('newsPage.contextNews'),
    favorite: tr('newsPage.favorite'),
    addFavorite: tr('newsPage.addFavorite'),
    favError: tr('newsPage.favError'),
    at: (day: string, h: string) => tr('newsPage.at', { day, h }),
    via: (p: string) => tr('newsPage.via', { p }),
    toneLabel: (t: string) => tr('newsPage.toneLabel', { t }),
    relPill: (r: number) => tr('newsPage.relPill', { r }),
    whyMatters: tr('newsPage.whyMatters'),
    summary: tr('newsPage.summary'),
    sourceLang: (l: string) => tr('newsPage.sourceLang', { l }),
    showOriginal: tr('newsPage.showOriginal'),
    hideOriginal: tr('newsPage.hideOriginal'),
    weight: tr('newsPage.weight'),
    toneScore: tr('newsPage.toneScore'),
    toneRange: tr('newsPage.toneRange'),
    todayOnTicker: tr('newsPage.todayOnTicker'),
    inLoadedFeed: tr('newsPage.inLoadedFeed'),
    noTicker: tr('newsPage.noTicker'),
    moreOn: (t: string) => tr('newsPage.moreOn', { t }),
    openArticle: tr('newsPage.openArticle'),
    copyLink: tr('newsPage.copyLink'),
    copied: tr('newsPage.copied'),
    noLink: tr('newsPage.noLink'),
    aiTitle: tr('newsPage.aiTitle'),
    aiIntro: (src: string) => tr('newsPage.aiIntro', { src }),
    aiButton: tr('newsPage.aiButton'),
    aiSteps: (src: string) => [tr('newsPage.aiSteps_open', { src }), tr('newsPage.aiSteps_extract'), tr('newsPage.aiSteps_write')],
    aiCancel: tr('newsPage.aiCancel'),
    aiRegenerate: tr('newsPage.aiRegenerate'),
    aiRetry: tr('newsPage.aiRetry'),
    aiKeyNumbers: tr('newsPage.aiKeyNumbers'),
    aiForPortfolio: tr('newsPage.aiForPortfolio'),
    aiModel: tr('newsPage.aiModel'),
    aiCost: tr('newsPage.aiCost'),
    aiWords: (n: number, s: string) => tr('newsPage.aiWords', { n, s }),
    aiSaved: (h: string) => tr('newsPage.aiSaved', { h }),
    aiNotConfigured: tr('newsPage.aiNotConfigured'),
    aiNotConfiguredHint: (v: string) => tr('newsPage.aiNotConfiguredHint', { v }),
    aiNoUrl: tr('newsPage.aiNoUrl'),
    aiUnreadable: tr('newsPage.aiUnreadable'),
    aiNoCredits: tr('newsPage.aiNoCredits'),
    aiFailed: tr('newsPage.aiFailed'),
    aiReasons: {
      paywall: (src: string) => tr('newsPage.aiReasons_paywall', { src }),
      blocked: (src: string) => tr('newsPage.aiReasons_blocked', { src }),
      too_short: () => tr('newsPage.aiReasons_too_short'),
      not_html: () => tr('newsPage.aiReasons_not_html'),
      fetch: () => tr('newsPage.aiReasons_fetch'),
      unsafe_url: () => tr('newsPage.aiReasons_unsafe_url'),
    } as Record<string, (src: string) => string>,
    sourcesTitle: tr('newsPage.sourcesTitle'),
    close: tr('newsPage.close'),
    lastRound: tr('newsPage.lastRound'),
    providers: tr('newsPage.providers'),
    coverageTitle: tr('newsPage.coverageTitle'),
    roundEnded: tr('newsPage.roundEnded'),
    roundRead: tr('newsPage.roundRead'),
    roundSaved: tr('newsPage.roundSaved'),
    roundDup: tr('newsPage.roundDup'),
    roundBlocked: tr('newsPage.roundBlocked'),
    roundBlockedList: tr('newsPage.roundBlockedList'),
    roundNext: tr('newsPage.roundNext'),
    roundEvery: (m: string) => tr('newsPage.roundEvery', { m }),
    roundState: tr('newsPage.roundState'),
    roundOk: tr('newsPage.roundOk'),
    roundDegraded: tr('newsPage.roundDegraded'),
    roundWaiting: tr('newsPage.roundWaiting'),
    roundError: tr('newsPage.roundError'),
    roundMissing: tr('newsPage.roundMissing'),
    ago: (m: number) => m < 1 ? tr('newsPage.ago_now') : m < 60 ? tr('newsPage.ago_min', { m }) : tr('newsPage.ago_h', { h: Math.floor(m / 60) }),
    notDeclared: tr('newsPage.notDeclared'),
    noProviders: tr('newsPage.noProviders'),
    muteSuspended: tr('newsPage.muteSuspended'),
    muteBudget: tr('newsPage.muteBudget'),
    covTickers: tr('newsPage.covTickers'),
    covRel: tr('newsPage.covRel'),
    covStored: tr('newsPage.covStored'),
    covMax: (n: number) => tr('newsPage.covMax', { n }),
    covSources: tr('newsPage.covSources'),
    sourcesExplain: [tr('newsPage.sourcesExplain_1'), tr('newsPage.sourcesExplain_2'), tr('newsPage.sourcesExplain_3')],
    muteNotDeclared: tr('newsPage.muteNotDeclared'),
    alerts: tr('newsPage.alerts'),
    alertsHead: tr('newsPage.alertsHead'),
    alertsOn: tr('newsPage.alertsOn'),
    alertsMin: tr('newsPage.alertsMin'),
    alertsScope: tr('newsPage.alertsScope'),
    scopePortfolio: tr('newsPage.scopePortfolio'),
    scopeFavorites: tr('newsPage.scopeFavorites'),
    alertsSystem: tr('newsPage.alertsSystem'),
    alertsHelp: tr('newsPage.alertsHelp'),
    alertsDenied: tr('newsPage.alertsDenied'),
    alertKicker: (r: number) => tr('newsPage.alertKicker', { r }),
    alertOpen: tr('newsPage.alertOpen'),
    alertClose: tr('newsPage.alertClose'),
    briefing: tr('newsPage.briefing'),
    briefingRewrite: tr('newsPage.briefingRewrite'),
    briefingWriting: tr('newsPage.briefingWriting'),
    briefingAt: (h: string) => tr('newsPage.briefingAt', { h }),
    briefingAge: (a: string) => a,
    briefingHours: (n: number) => tr('newsPage.briefingHours', { n }),
    briefingNews: (n: number) => tr('newsPage.briefingNews', { n }),
    briefingTokens: (n: string) => tr('newsPage.briefingTokens', { n }),
    briefingEmpty: tr('newsPage.briefingEmpty'),
    briefingLoading: tr('newsPage.briefingLoading'),
    briefingStale: tr('newsPage.briefingStale'),
    briefingLang: (l: string) => tr('newsPage.briefingLang', { l }),
    calendar: tr('newsPage.calendar'),
    events: (n: number) => n === 1 ? tr('newsPage.events_one') : tr('newsPage.events_other', { n }),
    calPeriods: { today: tr('newsPage.calPeriods_today'), tomorrow: tr('newsPage.calPeriods_tomorrow'), week: tr('newsPage.calPeriods_week'), "2weeks": tr('newsPage.calPeriods_2weeks') } as Record<string, string>,
    impHigh: tr('newsPage.impHigh'),
    impMedium: tr('newsPage.impMedium'),
    impAll: tr('newsPage.impAll'),
    colTime: tr('newsPage.colTime'),
    colArea: tr('newsPage.colArea'),
    colEvent: tr('newsPage.colEvent'),
    colPrev: tr('newsPage.colPrev'),
    colEst: tr('newsPage.colEst'),
    colAct: tr('newsPage.colAct'),
    importance: (n: number) => tr('newsPage.importance', { n }),
    dateEstimated: tr('newsPage.dateEstimated'),
    calSource: (s: string) => tr('newsPage.calSource', { s }),
    calOther: tr('newsPage.calOther'),
    countryUnknown: tr('newsPage.countryUnknown'),
    inPortfolio: tr('newsPage.inPortfolio'),
    calEmpty: tr('newsPage.calEmpty'),
    calEmptyHint: tr('newsPage.calEmptyHint'),
    calLoading: tr('newsPage.calLoading'),
    corporate: tr('newsPage.corporate'),
    corporateNote: tr('newsPage.corporateNote'),
    corporateEmpty: tr('newsPage.corporateEmpty'),
    corporateLoading: tr('newsPage.corporateLoading'),
    context: tr('newsPage.context'),
    ctxMacro: tr('newsPage.ctxMacro'),
    ctxGlobal: tr('newsPage.ctxGlobal'),
    ctxEmpty: tr('newsPage.ctxEmpty'),
    ctxLoading: tr('newsPage.ctxLoading'),
    allCategories: tr('newsPage.allCategories'),
    categories: { rates: tr('newsPage.categories_rates'), inflation: tr('newsPage.categories_inflation'), geopolitics: tr('newsPage.categories_geopolitics'), politics: tr('newsPage.categories_politics'), em: tr('newsPage.categories_em'), commodities: tr('newsPage.categories_commodities'), crypto: tr('newsPage.categories_crypto'), corporate: tr('newsPage.categories_corporate') } as Record<string, string>,
    errorPrefix: (op: string) => op,
    tonePill_pos: tr('newsPage.tonePill_pos'), tonePill_neg: tr('newsPage.tonePill_neg'), tonePill_neutral: tr('newsPage.tonePill_neutral'),
  };
}

type Dizionario = ReturnType<typeof costruisci>;
const cache = new Map<Lingua, Dizionario>();

export function parole(): Dizionario {
  const l = linguaCorrente();
  let d = cache.get(l);
  if (!d) { d = costruisci(l); cache.set(l, d); }
  return d;
}
