import { linguaCorrente, type Lingua } from '@/i18n/lingua';
import { traduci, type Chiave, type Parametri } from '@/i18n/t';
import type { Verbo } from '@/lib/cassa';

// I testi stanno nel catalogo (i18n/it|en/tradePage.ts): qui solo la forma che le viste usano.
function costruisci(l: Lingua) {
  const tr = (k: Chiave, p?: Record<string, string | number | null | undefined>) => traduci(l, k, p as Parametri | undefined);
  return {
    title: tr('tradePage.title'),
    cashAvailable: tr('tradePage.cashAvailable'),
    refresh: tr('tradePage.refresh'),
    newOrder: tr('tradePage.newOrder'),
    writesOfficial: tr('tradePage.writesOfficial'),
    verbs: { BUY: tr('tradePage.verbs_BUY'), ADD: tr('tradePage.verbs_ADD'), TRIM: tr('tradePage.verbs_TRIM'), SELL: tr('tradePage.verbs_SELL'), DIVIDEND: tr('tradePage.verbs_DIVIDEND') } as Record<Verbo, string>,
    gloss: { BUY: tr('tradePage.gloss_BUY'), ADD: tr('tradePage.gloss_ADD'), TRIM: tr('tradePage.gloss_TRIM'), SELL: tr('tradePage.gloss_SELL'), DIVIDEND: tr('tradePage.gloss_DIVIDEND') } as Record<Verbo, string>,
    instrument: tr('tradePage.instrument'),
    searchPlaceholder: tr('tradePage.searchPlaceholder'),
    inPortfolio: tr('tradePage.inPortfolio'),
    newName: tr('tradePage.newName'),
    suggestHeld: tr('tradePage.suggestHeld'),
    suggestMarket: tr('tradePage.suggestMarket'),
    suggestSearching: tr('tradePage.suggestSearching'),
    suggestNone: tr('tradePage.suggestNone'),
    suggestError: tr('tradePage.suggestError'),
    suggestHint: tr('tradePage.suggestHint'),
    suggestLabel: tr('tradePage.suggestLabel'),
    heldShares: (q: string) => tr('tradePage.heldShares', { q }),
    currencyFromQuote: (c: string) => tr('tradePage.currencyFromQuote', { c }),
    currencyUnsupported: (c: string) => tr('tradePage.currencyUnsupported', { c }),
    shares: tr('tradePage.shares'),
    live: (v: string) => tr('tradePage.live', { v }),
    total: tr('tradePage.total'),
    totalProceeds: tr('tradePage.totalProceeds'),
    totalEmpty: tr('tradePage.totalEmpty'),
    fxRate: (r: string) => tr('tradePage.fxRate', { r }),
    rationale: tr('tradePage.rationale'),
    rationaleHint: tr('tradePage.rationaleHint'),
    details: tr('tradePage.details'),
    detailsNow: tr('tradePage.detailsNow'),
    detailsDated: (d: string) => tr('tradePage.detailsDated', { d }),
    detailsManual: tr('tradePage.detailsManual'),
    detailsUnknown: tr('tradePage.detailsUnknown'),
    detailsLinked: (id: string) => tr('tradePage.detailsLinked', { id }),
    detailsDivergence: tr('tradePage.detailsDivergence'),
    execDate: tr('tradePage.execDate'),
    execTime: tr('tradePage.execTime'),
    divergence: tr('tradePage.divergence'),
    divergenceHelp: tr('tradePage.divergenceHelp'),
    identity: tr('tradePage.identity'),
    submit: (v: string) => tr('tradePage.submit', { v }),
    moreInfo: tr('tradePage.moreInfo'),
    checking: tr('tradePage.checking'),
    writing: tr('tradePage.writing'),
    sending: tr('tradePage.sending'),
    preview: tr('tradePage.preview'),
    previewMarket: tr('tradePage.previewMarket'),
    previewProxy: tr('tradePage.previewProxy'),
    cash: tr('tradePage.cash'),
    restInCash: tr('tradePage.restInCash'),
    usedByOrder: tr('tradePage.usedByOrder'),
    beyondCash: tr('tradePage.beyondCash'),
    enteringCash: tr('tradePage.enteringCash'),
    ofCash: (p: string) => tr('tradePage.ofCash', { p }),
    inCash: tr('tradePage.inCash'),
    position: (t: string) => tr('tradePage.position', { t }),
    positionGeneric: tr('tradePage.positionGeneric'),
    cost: tr('tradePage.cost'),
    weight: tr('tradePage.weight'),
    nav: tr('tradePage.nav'),
    from: (v: string) => tr('tradePage.from', { v }),
    waiting: tr('tradePage.waiting'),
    unchanged: tr('tradePage.unchanged'),
    newPosition: tr('tradePage.newPosition'),
    sizeTimes: (x: string, m: string) => tr('tradePage.sizeTimes', { x, m }),
    sizeAboveMax: (m: string) => tr('tradePage.sizeAboveMax', { m }),
    sizeBelowMax: (m: string) => tr('tradePage.sizeBelowMax', { m }),
    sizeBasis: (n: number) => tr('tradePage.sizeBasis', { n }),
    sizeEmpty: (m: string) => tr('tradePage.sizeEmpty', { m }),
    sizeEmptyNoHistory: tr('tradePage.sizeEmptyNoHistory'),
    sizeChart: tr('tradePage.sizeChart'),
    portfolio: tr('tradePage.portfolio'),
    portfolioNote: (n: number) => n === 1 ? tr('tradePage.portfolioNote_one') : tr('tradePage.portfolioNote_other', { n }),
    colTitle: tr('tradePage.colTitle'),
    colValue: tr('tradePage.colValue'),
    colPl: tr('tradePage.colPl'),
    carry: (q: string, c: string, w: string) => tr('tradePage.carry', { q, c, w }),
    recent: tr('tradePage.recent'),
    recentNote: tr('tradePage.recentNote'),
    now: tr('tradePage.now'),
    cashMovement: tr('tradePage.cashMovement'),
    cashTwr: tr('tradePage.cashTwr'),
    deposit: tr('tradePage.deposit'),
    withdraw: tr('tradePage.withdraw'),
    recordDeposit: tr('tradePage.recordDeposit'),
    recordWithdrawal: tr('tradePage.recordWithdrawal'),
    confirmIntentional: tr('tradePage.confirmIntentional'),
    cancel: tr('tradePage.cancel'),
    record: (v: string) => tr('tradePage.record', { v }),
    recordBalance: tr('tradePage.recordBalance'),
    amountHint: tr('tradePage.amountHint'),
    effect: tr('tradePage.effect'),
    flowsTwr: tr('tradePage.flowsTwr'),
    valueDate: tr('tradePage.valueDate'),
    today: tr('tradePage.today'),
    confirmNote: tr('tradePage.confirmNote'),
    deposited: tr('tradePage.deposited'),
    withdrawn: tr('tradePage.withdrawn'),
    movements: tr('tradePage.movements'),
    flowsChart: tr('tradePage.flowsChart'),
    flowsChartNote: tr('tradePage.flowsChartNote'),
    flowsChartLabel: (n: number, last: string) => tr('tradePage.flowsChartLabel', { n, last }),
    register: tr('tradePage.register'),
    registerCount: (n: number) => n === 1 ? tr('tradePage.registerCount_one') : tr('tradePage.registerCount_other', { n }),
    colMove: tr('tradePage.colMove'),
    colSize: tr('tradePage.colSize'),
    colAmount: tr('tradePage.colAmount'),
    colFlows: tr('tradePage.colFlows'),
    flowsFoot: tr('tradePage.flowsFoot'),
    openingTitle: tr('tradePage.openingTitle'),
    openingPill: tr('tradePage.openingPill'),
    openingIntro: tr('tradePage.openingIntro'),
    groupInstrument: tr('tradePage.groupInstrument'),
    groupBalance: tr('tradePage.groupBalance'),
    groupDocs: tr('tradePage.groupDocs'),
    optional: tr('tradePage.optional'),
    openingNamePh: tr('tradePage.openingNamePh'),
    openingTickerPh: tr('tradePage.openingTickerPh'),
    precisionDay: tr('tradePage.precisionDay'),
    precisionSecond: tr('tradePage.precisionSecond'),
    verifyBalance: tr('tradePage.verifyBalance'),
    registers: tr('tradePage.registers'),
    registersList: [tr('tradePage.registersList_1'), tr('tradePage.registersList_2'), tr('tradePage.registersList_3')],
    notCreates: tr('tradePage.notCreates'),
    notCreatesList: [tr('tradePage.notCreatesList_1'), tr('tradePage.notCreatesList_2'), tr('tradePage.notCreatesList_3')],
    coverage: tr('tradePage.coverage'),
    coverageShort: tr('tradePage.coverageShort'),
    coverageMore: tr('tradePage.coverageMore'),
    openingRegister: tr('tradePage.openingRegister'),
    openingCount: (n: number) => n === 1 ? tr('tradePage.openingCount_one') : tr('tradePage.openingCount_other', { n }),
    openingEmptyTitle: tr('tradePage.openingEmptyTitle'),
    openingEmpty: tr('tradePage.openingEmpty'),
    openingKnownAt: (d: string) => tr('tradePage.openingKnownAt', { d }),
    receipt: (id: number) => tr('tradePage.receipt', { id }),
    readBackOk: tr('tradePage.readBackOk'),
    nextBalance: tr('tradePage.nextBalance'),
    readBack: (t: string) => tr('tradePage.readBack', { t }),
  };
}

type Parole = ReturnType<typeof costruisci>;
const cache = new Map<Lingua, Parole>();

export function parole(): Parole {
  const l = linguaCorrente();
  let d = cache.get(l);
  if (!d) { d = costruisci(l); cache.set(l, d); }
  return d;
}
